---
- name: Create a directory for registry volume. 
  file: path=/srv/docker/images state=directory mode=0755

#  Disable selinux on common/task/main.yml
#- name: chcon on /srv/docker/images for container to write in.
#  shell: chcon -Rt svirt_sandbox_file_t /srv/docker/images

- name: Run a private docker registry - D'Artagnan
  docker_container:
    name: dartagnan
    state: started
    image: registry:2
    ports:
      - "{{ registry_ip }}:{{ registry_port }}:5000/tcp"
    volumes:
      - /srv/docker/images:/var/lib/registry:rw
...
