---
# installing docker from docker repo is more complicated 
# to set up docker daemon so not using it. - Heechul
#- name: Add docker yum repository
#  yum_repository:
#    name: docker
#    description: Docker repository
#    file: docker
#    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
#    enabled: yes
#    gpgcheck: yes
#    gpgkey: https://yum.dockerproject.org/gpg
#    
#- name: Install docker container engine package
#  yum: name=docker-engine state=latest

- name: Install docker container engine package
  yum: name={{ item }} state=latest
  with_items:
    - docker
    - python-pip

- name: Put /etc/sysconfig/docker file.
  template: src=docker.j2 dest=/etc/sysconfig/docker 
#  lineinfile: dest=/etc/sysconfig/docker regexp='^OPTIONS=' 
#      line="OPTIONS='--selinux-enabled --log-driver=journald -G dockerroot'"

- name: Check for {{ docker_devs }}
  command: parted -s {{ docker_devs }} print {{ docker_devs_partno }}
  register: docker_lvm
  failed_when: docker_lvm.rc is not defined
  changed_when: >
    docker_lvm.stdout == "Error: partition does not exists."

- name: Get the free space for {{ docker_devs }}
  shell: "parted -m {{ docker_devs }} unit s print free|grep 'free;' |tail -1 |cut -f2 -d':'"
  register: mkpart_start

- name: Create {{ docker_devs }}{{ docker_devs_partno }}
  command: parted -s {{ docker_devs }} mkpart primary {{ mkpart_start.stdout }} 100%
  when: docker_lvm.rc != 0

- name: Add LVM flag to {{ docker_devs}}{{ docker_devs_partno }}
  command: parted -s {{ docker_devs}} set {{ docker_devs_partno }} lvm on
  when: docker_lvm.rc != 0

- name: Create VG docker with PV {{ docker_devs }}{{ docker_devs_partno }}
  lvg: vg=docker pvs={{ docker_devs }}{{docker_devs_partno }}

- name: Put /etc/sysconfig/docker-storage-setup file.
  template: src=docker-storage-setup.j2 dest=/etc/sysconfig/docker-storage-setup

- name: Run docker-storage-setup
  command: docker-storage-setup

- name: Enable and Start docker
  service: name=docker state=restarted enabled=yes

- name: Set up the operator user 'ucim' other than root
  user: name=ucim comment="UCIM user" groups=wheel,dockerroot append=yes
      password={{ ucim_password }}

- name: Install docker-py module.
  shell: /usr/bin/pip install docker-py

#- name: Inline-Edit sudoers of wheel group.
#  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
...
